azure:
  redirect_uri: 'http://localhost:5000/authorize/azure/callback'
  tenant_id: 35def8fb-9e1f-49bf-8066-da907d23cf45
  scope: [User.Read, Files.ReadWrite]
  yir_folder_path: 'videos/yir clips'

gphotos:
  redirect_uri: ['http://localhost']
  javascript_origins: ["http://127.0.0.1:8000","http://localhost:8000"]    
  project_id: 'nello-yir'
  scope: ['https://www.googleapis.com/auth/photoslibrary.readonly', 'https://www.googleapis.com/auth/photoslibrary.sharing']