# specific folder structure and file naming
[local_storage]
quarantine = "Quarantine"

[local_storage.onedrive]
videos = "Videos"

[local_storage.google_drive]
videos = "Videos"
shortcuts = ".shortcuts-targets-by-id"

[local_storage.adobe]
projects = "Reviews"
reviews = "Year End"
project = "YIR"
bin = "Videos"
common = "_Common"
label_preset = "Nello YIR"

[ssd]
name = 'Nello Drive'
videos = 'Videos'


# executables for Windows and Mac
[executables]

[executables.windows]

[executables.windows.google_drive]
vendor = "Google"
name = "Drive File Stream"
exe = "GoogleDriveFS"

[executables.windows.drobpox]
vendor = "Dropbox"
name = "Client"
exe = "Dropbox"

[executables.windows.premiere]
vendor = "Adobe"
name = "Adobe Premiere Pro"
exe = "Adobe Premiere Pro"

[executables.windows.chrome]
vendor = "Google"
name = "Chrome"
exe = "chrome"

[executables.windows.edge]
vendor = "Microsoft"
name = "Edge"
exe = ["msedge", "msedgedriver"]

[executables.macos]

[executables.macos.google_drive]
name = "GoogleDrive"

[executables.macos.dropbox]
name = "Dropbox"

[executables.macos.onedrive]
name = "OneDrive"

[executables.macos.premiere]
name = "Adobe Premiere Pro"

[executables.macos.chrome]
name = "Google Chrome"

[executables.macos.edge]
name = "Microsoft Edge"


# browser user data
[user_data]
chrome = "Google/Chrome"
edge = "Microsoft/Edge"